{{- $namespace := .Values.namespace -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reporter-ingress
  namespace: {{ $namespace }}
  {{- if and .Values.ingress .Values.ingress.tls .Values.ingress.tls.azureKeyVaultURI }}
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: {{ .Values.ingress.tls.azureKeyVaultURI }}
  {{- end }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - {{ .Values.hostname }}
      {{- if and .Values.ingress .Values.ingress.tls .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reporter-service-http
                port:
                  number: 80 