name: Release Helm chart

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'           # only re-run when a chart changes
  workflow_dispatch:          # allow manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:              # fine-grained permissions
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0        # CR needs tags & history

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      env:
        CR_PACKAGE_PATH: .cr-release-packages
        CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-{{ .Version }}"
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
